# ██████╗  ██████╗ █████╗
# ██╔══██╗██╔════╝██╔══██╗
# ██║  ██║██║     ███████║
# ██║  ██║██║     ██╔══██║
# ██████╔╝╚██████╗██║  ██║
# ╚═════╝  ╚═════╝╚═╝  ╚═╝
# DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUTOMACAO
# UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE, NATAL/RN
#
# (C) 2022-2025 CARLOS M D VIEGAS
# https://github.com/cmdviegas

name: ${STACK_NAME}

x-hadoop-common:
  &hadoop-common
  image: hadoopcluster/${IMAGE_NAME}
  tty: true
  restart: on-failure
  entrypoint: ./bootstrap.sh
  networks:
    - hadoop_network
  volumes:
    - ./myfiles:/home/${CONTAINER_USERNAME}/myfiles

services:



  worker:
    <<: *hadoop-common
    deploy:
      mode: replicated
      replicas: ${NUM_WORKER_NODES}
    command: WORKER
    
  hadoop-master:
    <<: *hadoop-common
    container_name: hadoop-master
    hostname: hadoop-master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${CONTAINER_USERNAME} # USERNAME (change at .env file)
        PASS: ${CONTAINER_PASSWORD} # PASSWORD (change at .env file)
        HADOOP_VER: ${HADOOP_VERSION}
    ports:
      - "9870:9870/tcp" # HDFS
      - "8088:8088/tcp" # YARN
    volumes:
      - master:/home/${CONTAINER_USERNAME}/
    command: MASTER

networks:
  hadoop_network:
    name: hadoop_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24

volumes:
  master:
    name: master_volume
    driver: local
