# ██████╗  ██████╗ █████╗
# ██╔══██╗██╔════╝██╔══██╗
# ██║  ██║██║     ███████║
# ██║  ██║██║     ██╔══██║
# ██████╔╝╚██████╗██║  ██║
# ╚═════╝  ╚═════╝╚═╝  ╚═╝
# DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUTOMACAO
# UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE, NATAL/RN
#
# (C) 2022-2025 CARLOS M D VIEGAS
# https://github.com/cmdviegas

name: ${STACK_NAME}

x-common:
  &common
  image: ${IMAGE_NAME}
  tty: true
  restart: on-failure
  entrypoint: ["./bootstrap.sh"]
  networks:
    - hadoop_network

services:
  worker:
    <<: *common
    deploy:
      mode: replicated
      replicas: ${NUM_WORKER_NODES}
    volumes:
      - ./myfiles:/home/${MY_USERNAME}/myfiles
      - .env:/home/${MY_USERNAME}/.env
    command: ["WORKER"]
    
  master:
    <<: *common
    container_name: hadoop-master
    hostname: hadoop-master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MY_USERNAME: ${MY_USERNAME} # USERNAME (change at .env file)
        MY_PASSWORD: ${MY_PASSWORD} # PASSWORD (change at .env file)
        HADOOP_VERSION: ${HADOOP_VERSION}
    ports:
      - "9870:9870/tcp" # HDFS
      - "8088:8088/tcp" # YARN
      - "19888:19888/tcp" # JOB HISTORY
    volumes:
      - master:/home/${MY_USERNAME}/
      - ./myfiles:/home/${MY_USERNAME}/myfiles
      - .env:/home/${MY_USERNAME}/.env
    command: ["MASTER"]

networks:
  hadoop_network:
    name: hadoop_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  master:
    name: ${STACK_NAME}_master_volume
    driver: local
