# ██████╗  ██████╗ █████╗
# ██╔══██╗██╔════╝██╔══██╗
# ██║  ██║██║     ███████║
# ██║  ██║██║     ██╔══██║
# ██████╔╝╚██████╗██║  ██║
# ╚═════╝  ╚═════╝╚═╝  ╚═╝
# DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUTOMACAO
# UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE, NATAL/RN
#
# (C) 2024 CARLOS M D VIEGAS
# https://github.com/cmdviegas

### Description:
# This is a docker-compose file that creates a stack of nodes running Apache Hadoop 3.4.0.

### How it works:
# It initializes 'node-master' container with hadoop and spark services and multiple 'node-X' containers as worker nodes (according to the number of replicas). 'node-master' starts hadoop and spark services and then creates a cluster by connecting to each 'node-X'. There is an .env file that defines some environment variables that should be edited by the user.

version: '3.9'

services:
  node-master:
    container_name: node-master
    hostname: node-master
    image: hadoopcluster/${IMAGE_VER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${SYS_USERNAME} # USERNAME (change at .env file)
        PASS: ${SYS_PASSWORD} # USER PASSWORD (change at .env file)
    tty: true
    restart: no
    networks:
      hadoop_network:
        ipv4_address: ${IP_NODEMASTER}
    ports:
      - "9870:9870/tcp" # HDFS
      - "8088:8088/tcp" # YARN
      - "2222:22/tcp" # SSH
    volumes: 
      - ./apps:/home/${SYS_USERNAME}/apps
      - .env:/home/${SYS_USERNAME}/.env
      - node-master:/home/${SYS_USERNAME}/
    entrypoint: ./bootstrap.sh
    healthcheck:
      test: bash -c 'ssh -q -o ConnectTimeout=1 ${SYS_USERNAME}@node-master exit'
      start_period: 3s
      interval: 2s
      timeout: 3s
      retries: 3

  node:
    image: hadoopcluster/${IMAGE_VER}
    deploy:
      mode: replicated
      replicas: ${NODE_REPLICAS}
    tty: true
    restart: on-failure:2
    ports:
      - "8042-8062:8042/tcp" # YARN
    networks:
      - hadoop_network
    depends_on:
      node-master:
        condition: service_healthy
    entrypoint: ./bootstrap.sh
    volumes: 
      - ./apps:/home/${SYS_USERNAME}/apps
      - .env:/home/${SYS_USERNAME}/.env
      - /home/${SYS_USERNAME}/

networks:
  hadoop_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_RANGE}

volumes:
  node-master:
